# Site settings
title: mercuriete's blog
description: > # this means to ignore newlines until "baseurl:"
    A blackhole of knowledge I learnt by failing in my daily life projects
url: "https://mercuriete.github.io"
baseurl: ""
logo: mercuriete's <b>blog</b>
paginate: 5
paginate_path: "/page:num/"
owner:
    email: mercuriete@gmail.com
    facebook:
        show: false
        name: "Mercuriete"
        url: "https://fb.me/account"
    github:
        show: true
        username: "mercuriete"
    twitter:
        show: false
        username: ""
    disqus:
        show: false
        username: "account"
    linkedin:
        show: false
        profile: "https://linkedin.com/in/your-profile-id-here"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: redcarpet
highlighter: pygments
plugins:
    - jekyll-feed
    - jekyll-paginate
